services:
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6378:6378"  # Только локальный доступ
    networks:
      - live_shared_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:8002:8002"  # Только локальный доступ для nginx
    depends_on:
      - redis
    volumes:
      - ./app:/app/app:rw
      - ./certs/root.crt:/certs/root.crt:ro
    networks:
      - live_shared_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash","-c","rq worker default --url ${REDIS_URL:-redis://redis:6379/0}"]
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis
    volumes:
      - ./app:/app/app:rw
      - ./certs/root.crt:/certs/root.crt:ro
    networks:
      - live_shared_net

volumes:
  pgdata:

networks:
  live_shared_net:
    name: live_shared_net