services:
  redis:
    image: redis:7-alpine
    ports:
      - "6378:6378"
    networks:
      - live_shared_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8002:8002"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app:rw
      - ./certs/root.crt:/certs/root.crt:ro
    networks:
      - live_shared_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash","-c","rq worker default --url ${REDIS_URL:-redis://redis:6378/0}"]
    env_file:
      - ./.env
    depends_on:
      - backend
      - redis
    volumes:
      - ./app:/app/app:rw
      - ./certs/root.crt:/certs/root.crt:ro
    networks:
      - live_shared_net

  # frontend:
  #   build:
  #     context: ..
  #     dockerfile: frontend/Dockerfile
  #   env_file:
  #     - ../frontend/.env.local
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - backend

volumes:
  pgdata:


networks:
  live_shared_net:
    name: live_shared_net

